#!/bin/bash

set -e 

Github="https://github.com/lyc8503/sing-box-rules/releases/latest/download"

download_files() {
 
   cd /var/lib/sing-box-rules-db || exit
   echo "Fetching geoip.db and geosite.db "
   curl -LO "${1}/geo{ip,site,ip-cn}"
   rm -vf $(find . -maxdepth 1 -type f ! \( -name "geo*.db" -o -name "\.*" \))
}

download_files $Github

